using System;
using System.Linq;
using ProblemShare.Web.Entities;
using ProblemShare.Web.Interface;

namespace ProblemShare.Web.Business
{
    public class InstitutionBO : BO, IInstitutionBO
    {
        private const string DONT_USE_MSG = "Not to be used for now";

        public Guid Create(Guid ownerId, string name)
        {
            using (var db = Context)
            {
                var owner = db.Users.FirstOrDefault(x => x.UserId == ownerId);
                if (owner == null) return Guid.Empty;
                var dbI = new Institution()
                {
                    Name = name,
                    Owner = owner
                };
                db.Institutions.Add(dbI);
                db.SaveChanges();
                return dbI.InstitutionId; // Should automatically be generated by the database
            }
        }

        [Obsolete(DONT_USE_MSG)]
        public bool Delete(Guid id)
        {
            throw new NotImplementedException(DONT_USE_MSG);
        }

        public string GetName(Guid id)
        {
            using (var db = Context)
            {
                var dbI = db.Institutions.FirstOrDefault(x => x.InstitutionId == id);
                return dbI?.Name;
            }
        }

        public void UpdateName(Guid id, string name)
        {
            using (var db = Context)
            {
                var dbI = db.Institutions.FirstOrDefault(x => x.InstitutionId == id);
                if (dbI == null) return;
                dbI.Name = name;
                db.SaveChanges();
            }
        }
    }
}